
#' @title extract.scc
#' @description function for extracting posterior distributions generated by a simple intercept model tailored for single color controls
#' @param model a brms object
#' @param neg a character
#' @return a dataframe of posterior distributions
#' @examples \dontrun{
#' }
#' @export
 
extract.scc <- function(model, neg = "af"){
  post <- model %>% 
    brms::as_draws_df() %>%
    tibble::as_tibble() %>%
    dplyr::select(base::grep("^b_", base::colnames(.))) %>%
    dplyr::rename_with(.cols = tidyselect::everything(),
                .fn = ~stringr::str_remove(.x, "^b_"))
  # true negative
  # autofluorescence channel in the unstained sample
  a. <- post %>%
    dplyr::reframe(.ch = neg,
            .samp = neg,
            .val = Intercept)
  # autofluorescence spillover / channel background
  # fluorescent signal in each channel of the unstained control
  b. <- post %>%
    dplyr::select(Intercept, base::grep("^.ch", base::colnames(.))) %>%
    dplyr::select(-base::grep(":", base::colnames(.))) %>%
    dplyr::rename_with(.cols = everything(),
                .fn = ~str_remove(.x, "^.ch")) %>%
    tidyr::pivot_longer(-Intercept,
                 names_to = ".ch",
                 values_to = ".val") %>%
    dplyr::mutate(.val = Intercept + .val,
           .samp = "af") %>%
    dplyr::select(.ch, .samp, .val)
  # dye-induce autofluorescence
  # autofluorescent channel in each single color control
  c. <- post %>%
    dplyr::select(Intercept, base::grep("^.samp", base::colnames(.))) %>%
    dplyr::select(-base::grep(":", base::colnames(.))) %>%
    dplyr::rename_with(.cols = tidyselect::everything(),
                .fn = ~stringr::str_remove(.x, "^.samp")) %>%
    tidyr::pivot_longer(-Intercept,
                 names_to = ".samp",
                 values_to = ".val") %>%
    dplyr::mutate(.val = Intercept + .val,
           .ch = neg) %>%
    dplyr::select(.ch, .samp, .val)
  # fluorescent spillover
  # each of the fluorescent channels for each of the single color controls
  d. <- post %>%
    dplyr::select(Intercept, base::grep(":", base::colnames(.))) %>%
    dplyr::rename_with(.cols = tidyselect::everything(),
                .fn = ~stringr::str_remove(.x, "^.samp")) %>%
    dplyr::rename_with(.cols = tidyselect::everything(),
                .fn = ~stringr::str_remove(.x, ".ch")) %>%
    tidyr::pivot_longer(-Intercept,
                 names_to = ".samp.ch",
                 values_to = ".val") %>%
    tidyr::separate(col = .samp.ch,
             into = base::c(".samp", ".ch"),
             sep = ":") %>%
    dplyr::select(.ch, .samp, .val)
  # bind the extracted distributions back together
  data <- base::rbind(a., b., c., d.)
  return(data)
}